// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto

#include "message.pb.h"
#include "message.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace message {

static const char* VerifyService_method_names[] = {
  "/message.VerifyService/GetVerifyCode",
};

std::unique_ptr< VerifyService::Stub> VerifyService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VerifyService::Stub> stub(new VerifyService::Stub(channel, options));
  return stub;
}

VerifyService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetVerifyCode_(VerifyService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VerifyService::Stub::GetVerifyCode(::grpc::ClientContext* context, const ::message::GetVerifyReq& request, ::message::GetVerifyRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::GetVerifyReq, ::message::GetVerifyRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetVerifyCode_, context, request, response);
}

void VerifyService::Stub::async::GetVerifyCode(::grpc::ClientContext* context, const ::message::GetVerifyReq* request, ::message::GetVerifyRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::GetVerifyReq, ::message::GetVerifyRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVerifyCode_, context, request, response, std::move(f));
}

void VerifyService::Stub::async::GetVerifyCode(::grpc::ClientContext* context, const ::message::GetVerifyReq* request, ::message::GetVerifyRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVerifyCode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::GetVerifyRsp>* VerifyService::Stub::PrepareAsyncGetVerifyCodeRaw(::grpc::ClientContext* context, const ::message::GetVerifyReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::GetVerifyRsp, ::message::GetVerifyReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetVerifyCode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::GetVerifyRsp>* VerifyService::Stub::AsyncGetVerifyCodeRaw(::grpc::ClientContext* context, const ::message::GetVerifyReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetVerifyCodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

VerifyService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VerifyService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VerifyService::Service, ::message::GetVerifyReq, ::message::GetVerifyRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VerifyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::GetVerifyReq* req,
             ::message::GetVerifyRsp* resp) {
               return service->GetVerifyCode(ctx, req, resp);
             }, this)));
}

VerifyService::Service::~Service() {
}

::grpc::Status VerifyService::Service::GetVerifyCode(::grpc::ServerContext* context, const ::message::GetVerifyReq* request, ::message::GetVerifyRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* StatusService_method_names[] = {
  "/message.StatusService/GetChatServer",
  "/message.StatusService/Login",
  "/message.StatusService/RegisterChatServer",
  "/message.StatusService/Heartbeat",
  "/message.StatusService/ReportUserOnline",
  "/message.StatusService/ReportUserOffline",
  "/message.StatusService/QueryUserRoute",
};

std::unique_ptr< StatusService::Stub> StatusService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StatusService::Stub> stub(new StatusService::Stub(channel, options));
  return stub;
}

StatusService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetChatServer_(StatusService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Login_(StatusService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegisterChatServer_(StatusService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Heartbeat_(StatusService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReportUserOnline_(StatusService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReportUserOffline_(StatusService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryUserRoute_(StatusService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StatusService::Stub::GetChatServer(::grpc::ClientContext* context, const ::message::GetChatServerReq& request, ::message::GetChatServerRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::GetChatServerReq, ::message::GetChatServerRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetChatServer_, context, request, response);
}

void StatusService::Stub::async::GetChatServer(::grpc::ClientContext* context, const ::message::GetChatServerReq* request, ::message::GetChatServerRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::GetChatServerReq, ::message::GetChatServerRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetChatServer_, context, request, response, std::move(f));
}

void StatusService::Stub::async::GetChatServer(::grpc::ClientContext* context, const ::message::GetChatServerReq* request, ::message::GetChatServerRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetChatServer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::GetChatServerRsp>* StatusService::Stub::PrepareAsyncGetChatServerRaw(::grpc::ClientContext* context, const ::message::GetChatServerReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::GetChatServerRsp, ::message::GetChatServerReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetChatServer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::GetChatServerRsp>* StatusService::Stub::AsyncGetChatServerRaw(::grpc::ClientContext* context, const ::message::GetChatServerReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetChatServerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StatusService::Stub::Login(::grpc::ClientContext* context, const ::message::LoginReq& request, ::message::LoginRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::LoginReq, ::message::LoginRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void StatusService::Stub::async::Login(::grpc::ClientContext* context, const ::message::LoginReq* request, ::message::LoginRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::LoginReq, ::message::LoginRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void StatusService::Stub::async::Login(::grpc::ClientContext* context, const ::message::LoginReq* request, ::message::LoginRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::LoginRsp>* StatusService::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::message::LoginReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::LoginRsp, ::message::LoginReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::LoginRsp>* StatusService::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::message::LoginReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StatusService::Stub::RegisterChatServer(::grpc::ClientContext* context, const ::message::RegisterChatServerReq& request, ::message::RegisterChatServerRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::RegisterChatServerReq, ::message::RegisterChatServerRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterChatServer_, context, request, response);
}

void StatusService::Stub::async::RegisterChatServer(::grpc::ClientContext* context, const ::message::RegisterChatServerReq* request, ::message::RegisterChatServerRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::RegisterChatServerReq, ::message::RegisterChatServerRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterChatServer_, context, request, response, std::move(f));
}

void StatusService::Stub::async::RegisterChatServer(::grpc::ClientContext* context, const ::message::RegisterChatServerReq* request, ::message::RegisterChatServerRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterChatServer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::RegisterChatServerRsp>* StatusService::Stub::PrepareAsyncRegisterChatServerRaw(::grpc::ClientContext* context, const ::message::RegisterChatServerReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::RegisterChatServerRsp, ::message::RegisterChatServerReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterChatServer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::RegisterChatServerRsp>* StatusService::Stub::AsyncRegisterChatServerRaw(::grpc::ClientContext* context, const ::message::RegisterChatServerReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterChatServerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StatusService::Stub::Heartbeat(::grpc::ClientContext* context, const ::message::HeartbeatReq& request, ::message::HeartbeatRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::HeartbeatReq, ::message::HeartbeatRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Heartbeat_, context, request, response);
}

void StatusService::Stub::async::Heartbeat(::grpc::ClientContext* context, const ::message::HeartbeatReq* request, ::message::HeartbeatRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::HeartbeatReq, ::message::HeartbeatRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Heartbeat_, context, request, response, std::move(f));
}

void StatusService::Stub::async::Heartbeat(::grpc::ClientContext* context, const ::message::HeartbeatReq* request, ::message::HeartbeatRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Heartbeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::HeartbeatRsp>* StatusService::Stub::PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::message::HeartbeatReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::HeartbeatRsp, ::message::HeartbeatReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Heartbeat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::HeartbeatRsp>* StatusService::Stub::AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::message::HeartbeatReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHeartbeatRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StatusService::Stub::ReportUserOnline(::grpc::ClientContext* context, const ::message::ReportUserOnlineReq& request, ::message::ReportUserOnlineRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::ReportUserOnlineReq, ::message::ReportUserOnlineRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReportUserOnline_, context, request, response);
}

void StatusService::Stub::async::ReportUserOnline(::grpc::ClientContext* context, const ::message::ReportUserOnlineReq* request, ::message::ReportUserOnlineRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::ReportUserOnlineReq, ::message::ReportUserOnlineRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportUserOnline_, context, request, response, std::move(f));
}

void StatusService::Stub::async::ReportUserOnline(::grpc::ClientContext* context, const ::message::ReportUserOnlineReq* request, ::message::ReportUserOnlineRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportUserOnline_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::ReportUserOnlineRsp>* StatusService::Stub::PrepareAsyncReportUserOnlineRaw(::grpc::ClientContext* context, const ::message::ReportUserOnlineReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::ReportUserOnlineRsp, ::message::ReportUserOnlineReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReportUserOnline_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::ReportUserOnlineRsp>* StatusService::Stub::AsyncReportUserOnlineRaw(::grpc::ClientContext* context, const ::message::ReportUserOnlineReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReportUserOnlineRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StatusService::Stub::ReportUserOffline(::grpc::ClientContext* context, const ::message::ReportUserOfflineReq& request, ::message::ReportUserOfflineRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::ReportUserOfflineReq, ::message::ReportUserOfflineRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReportUserOffline_, context, request, response);
}

void StatusService::Stub::async::ReportUserOffline(::grpc::ClientContext* context, const ::message::ReportUserOfflineReq* request, ::message::ReportUserOfflineRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::ReportUserOfflineReq, ::message::ReportUserOfflineRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportUserOffline_, context, request, response, std::move(f));
}

void StatusService::Stub::async::ReportUserOffline(::grpc::ClientContext* context, const ::message::ReportUserOfflineReq* request, ::message::ReportUserOfflineRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportUserOffline_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::ReportUserOfflineRsp>* StatusService::Stub::PrepareAsyncReportUserOfflineRaw(::grpc::ClientContext* context, const ::message::ReportUserOfflineReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::ReportUserOfflineRsp, ::message::ReportUserOfflineReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReportUserOffline_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::ReportUserOfflineRsp>* StatusService::Stub::AsyncReportUserOfflineRaw(::grpc::ClientContext* context, const ::message::ReportUserOfflineReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReportUserOfflineRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StatusService::Stub::QueryUserRoute(::grpc::ClientContext* context, const ::message::QueryUserRouteReq& request, ::message::QueryUserRouteRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::QueryUserRouteReq, ::message::QueryUserRouteRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryUserRoute_, context, request, response);
}

void StatusService::Stub::async::QueryUserRoute(::grpc::ClientContext* context, const ::message::QueryUserRouteReq* request, ::message::QueryUserRouteRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::QueryUserRouteReq, ::message::QueryUserRouteRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryUserRoute_, context, request, response, std::move(f));
}

void StatusService::Stub::async::QueryUserRoute(::grpc::ClientContext* context, const ::message::QueryUserRouteReq* request, ::message::QueryUserRouteRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryUserRoute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::QueryUserRouteRsp>* StatusService::Stub::PrepareAsyncQueryUserRouteRaw(::grpc::ClientContext* context, const ::message::QueryUserRouteReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::QueryUserRouteRsp, ::message::QueryUserRouteReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryUserRoute_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::QueryUserRouteRsp>* StatusService::Stub::AsyncQueryUserRouteRaw(::grpc::ClientContext* context, const ::message::QueryUserRouteReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryUserRouteRaw(context, request, cq);
  result->StartCall();
  return result;
}

StatusService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StatusService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StatusService::Service, ::message::GetChatServerReq, ::message::GetChatServerRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StatusService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::GetChatServerReq* req,
             ::message::GetChatServerRsp* resp) {
               return service->GetChatServer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StatusService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StatusService::Service, ::message::LoginReq, ::message::LoginRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StatusService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::LoginReq* req,
             ::message::LoginRsp* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StatusService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StatusService::Service, ::message::RegisterChatServerReq, ::message::RegisterChatServerRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StatusService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::RegisterChatServerReq* req,
             ::message::RegisterChatServerRsp* resp) {
               return service->RegisterChatServer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StatusService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StatusService::Service, ::message::HeartbeatReq, ::message::HeartbeatRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StatusService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::HeartbeatReq* req,
             ::message::HeartbeatRsp* resp) {
               return service->Heartbeat(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StatusService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StatusService::Service, ::message::ReportUserOnlineReq, ::message::ReportUserOnlineRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StatusService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::ReportUserOnlineReq* req,
             ::message::ReportUserOnlineRsp* resp) {
               return service->ReportUserOnline(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StatusService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StatusService::Service, ::message::ReportUserOfflineReq, ::message::ReportUserOfflineRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StatusService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::ReportUserOfflineReq* req,
             ::message::ReportUserOfflineRsp* resp) {
               return service->ReportUserOffline(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StatusService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StatusService::Service, ::message::QueryUserRouteReq, ::message::QueryUserRouteRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StatusService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::QueryUserRouteReq* req,
             ::message::QueryUserRouteRsp* resp) {
               return service->QueryUserRoute(ctx, req, resp);
             }, this)));
}

StatusService::Service::~Service() {
}

::grpc::Status StatusService::Service::GetChatServer(::grpc::ServerContext* context, const ::message::GetChatServerReq* request, ::message::GetChatServerRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StatusService::Service::Login(::grpc::ServerContext* context, const ::message::LoginReq* request, ::message::LoginRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StatusService::Service::RegisterChatServer(::grpc::ServerContext* context, const ::message::RegisterChatServerReq* request, ::message::RegisterChatServerRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StatusService::Service::Heartbeat(::grpc::ServerContext* context, const ::message::HeartbeatReq* request, ::message::HeartbeatRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StatusService::Service::ReportUserOnline(::grpc::ServerContext* context, const ::message::ReportUserOnlineReq* request, ::message::ReportUserOnlineRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StatusService::Service::ReportUserOffline(::grpc::ServerContext* context, const ::message::ReportUserOfflineReq* request, ::message::ReportUserOfflineRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StatusService::Service::QueryUserRoute(::grpc::ServerContext* context, const ::message::QueryUserRouteReq* request, ::message::QueryUserRouteRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* ChatService_method_names[] = {
  "/message.ChatService/PushFriendRequests",
  "/message.ChatService/PushFriendList",
  "/message.ChatService/PushPrivateMessage",
};

std::unique_ptr< ChatService::Stub> ChatService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChatService::Stub> stub(new ChatService::Stub(channel, options));
  return stub;
}

ChatService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_PushFriendRequests_(ChatService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PushFriendList_(ChatService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PushPrivateMessage_(ChatService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ChatService::Stub::PushFriendRequests(::grpc::ClientContext* context, const ::message::PushFriendRequestsReq& request, ::message::PushFriendRequestsRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::PushFriendRequestsReq, ::message::PushFriendRequestsRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushFriendRequests_, context, request, response);
}

void ChatService::Stub::async::PushFriendRequests(::grpc::ClientContext* context, const ::message::PushFriendRequestsReq* request, ::message::PushFriendRequestsRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::PushFriendRequestsReq, ::message::PushFriendRequestsRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushFriendRequests_, context, request, response, std::move(f));
}

void ChatService::Stub::async::PushFriendRequests(::grpc::ClientContext* context, const ::message::PushFriendRequestsReq* request, ::message::PushFriendRequestsRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushFriendRequests_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::PushFriendRequestsRsp>* ChatService::Stub::PrepareAsyncPushFriendRequestsRaw(::grpc::ClientContext* context, const ::message::PushFriendRequestsReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::PushFriendRequestsRsp, ::message::PushFriendRequestsReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushFriendRequests_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::PushFriendRequestsRsp>* ChatService::Stub::AsyncPushFriendRequestsRaw(::grpc::ClientContext* context, const ::message::PushFriendRequestsReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushFriendRequestsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatService::Stub::PushFriendList(::grpc::ClientContext* context, const ::message::PushFriendListReq& request, ::message::PushFriendListRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::PushFriendListReq, ::message::PushFriendListRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushFriendList_, context, request, response);
}

void ChatService::Stub::async::PushFriendList(::grpc::ClientContext* context, const ::message::PushFriendListReq* request, ::message::PushFriendListRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::PushFriendListReq, ::message::PushFriendListRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushFriendList_, context, request, response, std::move(f));
}

void ChatService::Stub::async::PushFriendList(::grpc::ClientContext* context, const ::message::PushFriendListReq* request, ::message::PushFriendListRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushFriendList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::PushFriendListRsp>* ChatService::Stub::PrepareAsyncPushFriendListRaw(::grpc::ClientContext* context, const ::message::PushFriendListReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::PushFriendListRsp, ::message::PushFriendListReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushFriendList_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::PushFriendListRsp>* ChatService::Stub::AsyncPushFriendListRaw(::grpc::ClientContext* context, const ::message::PushFriendListReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushFriendListRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatService::Stub::PushPrivateMessage(::grpc::ClientContext* context, const ::message::PushPrivateMessageReq& request, ::message::PushPrivateMessageRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::message::PushPrivateMessageReq, ::message::PushPrivateMessageRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushPrivateMessage_, context, request, response);
}

void ChatService::Stub::async::PushPrivateMessage(::grpc::ClientContext* context, const ::message::PushPrivateMessageReq* request, ::message::PushPrivateMessageRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::message::PushPrivateMessageReq, ::message::PushPrivateMessageRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushPrivateMessage_, context, request, response, std::move(f));
}

void ChatService::Stub::async::PushPrivateMessage(::grpc::ClientContext* context, const ::message::PushPrivateMessageReq* request, ::message::PushPrivateMessageRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushPrivateMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::message::PushPrivateMessageRsp>* ChatService::Stub::PrepareAsyncPushPrivateMessageRaw(::grpc::ClientContext* context, const ::message::PushPrivateMessageReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::message::PushPrivateMessageRsp, ::message::PushPrivateMessageReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushPrivateMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::message::PushPrivateMessageRsp>* ChatService::Stub::AsyncPushPrivateMessageRaw(::grpc::ClientContext* context, const ::message::PushPrivateMessageReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushPrivateMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

ChatService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::message::PushFriendRequestsReq, ::message::PushFriendRequestsRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::PushFriendRequestsReq* req,
             ::message::PushFriendRequestsRsp* resp) {
               return service->PushFriendRequests(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::message::PushFriendListReq, ::message::PushFriendListRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::PushFriendListReq* req,
             ::message::PushFriendListRsp* resp) {
               return service->PushFriendList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::message::PushPrivateMessageReq, ::message::PushPrivateMessageRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::message::PushPrivateMessageReq* req,
             ::message::PushPrivateMessageRsp* resp) {
               return service->PushPrivateMessage(ctx, req, resp);
             }, this)));
}

ChatService::Service::~Service() {
}

::grpc::Status ChatService::Service::PushFriendRequests(::grpc::ServerContext* context, const ::message::PushFriendRequestsReq* request, ::message::PushFriendRequestsRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::PushFriendList(::grpc::ServerContext* context, const ::message::PushFriendListReq* request, ::message::PushFriendListRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::PushPrivateMessage(::grpc::ServerContext* context, const ::message::PushPrivateMessageReq* request, ::message::PushPrivateMessageRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace message
#include <grpcpp/ports_undef.inc>

